### ISSUE TITLE
No run result from certain benchmarks

### ISSUE THREAD

**Issue by DonggeLiu** [google/oss-fuzz-gen#132]
https://llm-exp.oss-fuzz.com/Result-reports/scheduled/2024-02-29-weekly-all/sample/output-wxwidgets-_z15wxgetfreememoryv/01

**Comment by cjx10** [comment]
Incorrect target name and target path.
For `wxwidgets`, `runner.cpp` was not compiled, only [`zip.cpp`](https://github.com/wxWidgets/wxWidgets/blob/master/tests/fuzz/ossfuzz.sh#L12)

**Comment by DonggeLiu** [comment]
FI's daily report contains the info about fuzz target, but 1) the fuzz target path is not consistent, and 2) it does not store the fuz target binary name yet.

Inconsistency:
Some projects' reports contain the full path (which is what we need):
https://storage.googleapis.com/oss-fuzz-introspector/abseil-cpp/inspector-report/20240305/summary.json
But others seem to use binary name:
https://storage.googleapis.com/oss-fuzz-introspector/wxwidgets/inspector-report/20240305/summary.json

Ideally, we need two info from the FI report:
1. Fuzz target path. In particular, some projects move the fuzz target during compilation. We need the fuzz target path before compilation, but FI usually provides the one after compilation.
2. Binary name, which can be different from fuzz target basename.

**Comment by DavidKorczynski** [comment]
> Ideally, we need two info from the FI report:
> 1. Fuzz target path.

Just to clarify, this refers to the source code path?

> Inconsistency:
> Some projects' reports contain the full path (which is what we need):
> https://storage.googleapis.com/oss-fuzz-introspector/abseil-cpp/inspector-report/20240305/summary.json
> But others seem to use binary name:
> https://storage.googleapis.com/oss-fuzz-introspector/wxwidgets/inspector-report/20240305/summary.json

Is the issue with `wxwidgets` or `abseil-cpp`, or both? wxwidgets has both the fuzzer binary name and the source code path: https://storage.googleapis.com/oss-fuzz-introspector/wxwidgets/inspector-report/20240318/fuzz_report.html -- abseil-cpp only has the source code path. To my understanding `wxwidgets` is good but `abseil-cpp` has issues, is this correctly understood?

**Comment by DonggeLiu** [comment]
Hi @DavidKorczynski!

> > 1. Fuzz target path.
> Just to clarify, this refers to the source code path?

Yes! The framework needs the **_source code path before compilation_** to locate the file and then replace its content with the LLM-generated fuzz target.
I recall that you explained that some projects move the files around while building the fuzz target. Hence, the path **before compilation** is required.  


> Is the issue with `wxwidgets` or `abseil-cpp`, or both? wxwidgets has both the fuzzer binary name and the source code path: https://storage.googleapis.com/oss-fuzz-introspector/wxwidgets/inspector-report/20240318/fuzz_report.html -- abseil-cpp only has the source code path. To my understanding `wxwidgets` is good but `abseil-cpp` has issues, is this correctly understood?

Yes! You are correct.
`wxwidgets` is good because it provides both **fuzz target binary name** and **fuzz target source code path**, which is needed by [its benchmark YAML](https://github.com/google/oss-fuzz-gen/blob/main/benchmark-sets/all/wxwidgets.yaml#L34-L35). In this particular case, our benchmark YAML is wrong because `runner.cpp` was never compiled. FI correctly provides `zip` and `/src/wxwidgets/tests/fuzz/zip.cpp`, precisely what we need.

Since `wxwidgets`'s [`summary.json`](https://storage.googleapis.com/oss-fuzz-introspector/wxwidgets/inspector-report/20240305/summary.json) does not have this info, what's the best way to retrieve this information? (E.g., other files in bucket, APIs, or libs? I presume parsing the `fuzz_report.html` is not a scalable idea.)

**Comment by DavidKorczynski** [comment]
Can you confirm `abseil-cpp` is looking good now? This is what I get when I generate a benchmark:

```yaml
"functions":
- "name": "_ZN4absl19str_format_internal13FormatArgImpl8DispatchIxEEbNS1_4DataENS0_24FormatConversionSpecImplEPv"
  "params":
  - "name": "arg"
    "type": "char *"
  - "name": "spec"
    "type": "size_t"
  - "name": "out"
    "type": "int"
  - "name": ""
    "type": "char *"
  "return_type": "bool"
  "signature": "bool absl::str_format_internal::FormatArgImpl::Dispatch<absl::str_format_internal::VoidPtr>(DW_TAG_union_typeData, FormatConversionSpecImpl, void *)"
- "name": "_ZN4absl19str_format_internal13FormatArgImpl8DispatchINS_6int128EEEbNS1_4DataENS0_24FormatConversionSpecImplEPv"
  "params":
  - "name": "arg"
    "type": "char *"
  - "name": "spec"
    "type": "size_t"
  - "name": "out"
    "type": "int"
  - "name": ""
    "type": "char *"
  "return_type": "bool"
  "signature": "bool absl::str_format_internal::FormatArgImpl::Dispatch<absl::Dispatch<absl::str_format_internal::VoidPtr>(DW_TAG_union_typeData, FormatConversionSpecImpl, void *)"
- "name": "_ZN4absl19str_format_internal17FormatConvertImplEwNS0_24FormatConversionSpecImplEPNS0_14FormatSinkImplE"
  "params":
  - "name": "v"
    "type": "int"
  - "name": "conv"
    "type": "size_t"
  - "name": "sink"
    "type": "int"
  - "name": ""
    "type": "absl::str_format_internal::FormatSinkImpl *"
  "return_type": "char"
  "signature": "CharConvertResult absl::str_format_internal::FormatConvertImpl(wchar_t, const FormatConversionSpecImpl, FormatSinkImpl *)"
"language": "c++"
"project": "abseil-cpp"
"target_name": "string_escape_fuzzer"
"target_path": "/src/string_escape_fuzzer.cc"
```
